apiVersion: v1
kind: Pod
metadata:
  name: petclinic-pod
  labels:
    zone: prod
    version: v1.1
spec:
  containers:
  - name: petclinic
    image: ganeshhp/maven-petclinic-project:latest
    ports:
    - containerPort: 8080
